import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'



import Navbar from '@/components/Navbar';
import Leftbar from '@/components/Leftbar';
import Main from '@/components/Main';
import Rightbar from '@/components/Rightbar';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [currentUser,setCurrentUser] = useState(false)
  // useEffect(()=>{
  //   if(!currentUser){
  //     Router.push("./login")
  //  }
  // },[])

  return (
    <>
      <Head>
        <title>SocMedia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className=' bg-gray-100  mx-auto' >
       <Navbar/>
       <div className=' flex items-start justify-between pt-1'>
        <Leftbar/>
        <Main/>
        <Rightbar/>
       </div>
      </main>
    </>
  )
}
